language: python
python:
  - "3.6"
os: linux
dist: xenial
script: python mc_chunk_get_V2_py_edition_final.py
before_install:
  - cd Linux/src
  - pip3 install --upgrade pip
  - pip3 install PyInstaller
  - sudo apt install xcb -y
install:
  - pip install -r requirements.txt