language: python
python:
  - "3.6"
os: linux
dist: xenial
script: python3 mc_chunk_get_V2_py_edition_final.py
before_install:
  - cd Linux/src
  - export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms
  - pip3 install --upgrade pip
  - pip3 install setuptools
  - pip3 install PyInstaller
  - sudo apt-get update 
  - sudo apt-get build-dep qt5-default
  - sudo apt-get install libx11-xcb-dev libglu1-mesa-dev build-essential
  - sudo apt-get install -qq libegl1-mesa
install:
  - pip install -r requirements.txt