language: python
python:
  - "3.6"
os: linux
dist: xenial
script: mc_chunk_get_V2_py_edition_final
before_install:
  - cd Linux/src
  - pip3 install --upgrade pip
install:
  - pip install -r requirements.txt